Add TSDoc to "promisifyEvent" - add TSDoc to "promisifyEvent" - add "service: mongodb" to travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,51 +1,52 @@
 language: node_js
+services: mongodb
 node_js: [
-        # check Latest
-        12,
-        # check LTS
-        10,
-        # check against oldest supported
-        8,
-    ]
+    # check Latest
+    12,
+    # check LTS
+    10,
+    # check against oldest supported
+    8,
+  ]
 script: | # this has to be used, otherwise it executes the tests twice (because of "default build script")
-    npm run mocha
-    if [ $? -ne 0 ]; then exit 1; fi # this is added because sometimes it fails and exists with 0 in travis
-    if [ $TRAVIS_NODE_VERSION == "12" ]; then npm run coverage; fi
+  npm run mocha
+  if [ $? -ne 0 ]; then exit 1; fi # this is added because sometimes it fails and exists with 0 in travis
+  if [ $TRAVIS_NODE_VERSION == "12" ]; then npm run coverage; fi
 stages:
-    - compile
-    - test
-    # - deploy
+  - compile
+  - test
+  # - deploy
 jobs:
-    include:
-        - name: "Test Compile Ability"
-          stage: compile
-          node_js: 10 # use version 10, because that speeds up the task, because travis's default is v10
-          script: |
-              (npm audit || exit 0)
-              npm run buildtests # build tests too to check if errors from tsc are present
-        # - name: 'Deploy to NPM'
-        #   stage: deploy
-        #   if: tag IS present AND NOT type IN (pull_request)
-        #   script: skip
-        #   deploy:
-        #     provider: npm
-        #     email: $DEPLOY_NPM_EMAIL
-        #     tag: latest
-        #     skip_cleanup: true
-        #     api_key: $DEPLOY_NPM_KEY
-        #     on:
-        #       tags: true
-        # - name: 'Deploy to GitHub Pages'
-        #   stage: deploy
-        #   if: branch IN (master, r6/master) AND NOT type IN (pull_request) # i know this redundant, but it is needed otherwise the test will always create a deploy of this
-        #   script: bash ./ghPagesPre.sh
-        #   deploy:
-        #     provider: pages
-        #     skip_cleanup: true
-        #     github_token: $GITHUB_GH_PAGES
-        #     keep_history: false
-        #     target_branch: gh-pages # i know this the default, but just to be sure
-        #     on:
-        #       branch:
-        #         - master
-        #         - r6/master
+  include:
+    - name: 'Test Compile Ability'
+      stage: compile
+      node_js: 10 # use version 10, because that speeds up the task, because travis's default is v10
+      script: |
+        (npm audit || exit 0)
+        npm run buildtests # build tests too to check if errors from tsc are present
+    # - name: 'Deploy to NPM'
+    #   stage: deploy
+    #   if: tag IS present AND NOT type IN (pull_request)
+    #   script: skip
+    #   deploy:
+    #     provider: npm
+    #     email: $DEPLOY_NPM_EMAIL
+    #     tag: latest
+    #     skip_cleanup: true
+    #     api_key: $DEPLOY_NPM_KEY
+    #     on:
+    #       tags: true
+    # - name: 'Deploy to GitHub Pages'
+    #   stage: deploy
+    #   if: branch IN (master, r6/master) AND NOT type IN (pull_request) # i know this redundant, but it is needed otherwise the test will always create a deploy of this
+    #   script: bash ./ghPagesPre.sh
+    #   deploy:
+    #     provider: pages
+    #     skip_cleanup: true
+    #     github_token: $GITHUB_GH_PAGES
+    #     keep_history: false
+    #     target_branch: gh-pages # i know this the default, but just to be sure
+    #     on:
+    #       branch:
+    #         - master
+    #         - r6/master
